<a href="https://colab.research.google.com/github/asupraja3/Python_basic/blob/main/Python_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
names = ["sup", "prav"]
names


['sup', 'prav']

In [ ]:
import math
math.floor(2.7)

2

In [ ]:
math.ceil(2.7)

3

In [ ]:
math.floor(2.7)

2

In [ ]:
from math import sqrt
sqrt(2)

1.4142135623730951

In [ ]:
~12

-13

In [ ]:
12 & 13

12

In [ ]:
a=2
b=3
a<3 & b<3

False

In [ ]:
a&b

2

In [ ]:
x = input("Enter 1st number:")
y = input("Enter 2nd number:")
z = x + y
print(z)

Enter 1st number:2
Enter 2nd number:2
22


In [ ]:
x = int(input("Enter 1st number:"))
y = int(input("Enter 2nd number:"))
z = x + y
print(z)

Enter 1st number:2
Enter 2nd number:2
4


In [ ]:
ch = input('Enter a character:') [0]
print(ch)

Enter a character:yu
y


In [ ]:
result = eval(input('Enter a character:'))
print(result)

Enter a character:2+2
4


In [ ]:
if False:
  print('it false')
elif True:
  print("I'm true")
print('Bye')

I'm true
Bye


In [ ]:
x = int(input('Enter x:'))
y = int(input('Enter y:'))
z = int(input('Enter z:'))
if x>y and x>z:
  print('x is greater')
elif y>x and y>z:
  print('y is greater')
else:
  print('z is greater')

Enter x:2
Enter y:3
Enter z:4
z is greater


In [ ]:
x = 1
j = 1
while x <= 5:
  print(x)
  while j<=5:
    print('hi',end="")
    j += 1
  x += 1
print('after while',x)

1
hihihihihi2
3
4
5
after while 6


In [ ]:
x = 1
while x <= 5:
  print(x,end="")
  j = 1
  while j<=5:
    print('hi',end="")
    j += 1
  x += 1
  print()
print('after while',x,j)

1hihihihihi
2hihihihihi
3hihihihihi
4hihihihihi
5hihihihihi
after while 6 6


In [ ]:
x = 1
while x <= 50:
  if x%3!=0 and x%5!=0:
    print(x,"  ",end="")
  x+=1
y = 1
print("\n")
while y <= 50:
  if y%3==0 or y%5==0:
    y+=1
    continue
  print(y,"  ",end="")
  y+=1

1   2   4   7   8   11   13   14   16   17   19   22   23   26   28   29   31   32   34   37   38   41   43   44   46   47   49   

1   2   4   7   8   11   13   14   16   17   19   22   23   26   28   29   31   32   34   37   38   41   43   44   46   47   49   

While works for iterations where for loop for working on list of values

In [ ]:
x = ['sup','prav','jana']
for i in x:
  print(i," ", end="")
print("")
for i in range(1,10):
  print(i," ", end="")
print("")
for i in range(1,10,2):
  print(i," ", end="")
print("")
for i in range(20,10,-2):
  print(i," ", end="")
print("")

sup  prav  jana  
1  2  3  4  5  6  7  8  9  
1  3  5  7  9  
20  18  16  14  12  


In [ ]:
av = 5
x = int(input('Enter a number:'))
i = 1
while i <= x:
  if i > av:
    print('out of stock')
    break
  print(i," ", end = " ")
  i+=1

Enter a number:6
1   2   3   4   5   out of stock


pass: we normally use to skip the function or method or condition

In [ ]:
for i in range(1,101):
  if i%2!=0:
    pass
  else:
    print(i," ", end="")

2  4  6  8  10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98  100  

In [ ]:
x = int(input('Enter a number:'))
for i in range(1,x+1):
  for j in range(4-i+1):
    print("*",end=" ")
  print("\n")

Enter a number:4
* * * * 

* * * 

* * 

* 



In [ ]:
x = int(input('Enter a number:'))
for i in range(1,x+1):
  for j in range(1,4-i+2):
    print(j,end=" ")
  print("\n")

Enter a number:4
1 2 3 4 

1 2 3 

1 2 

1 



In [ ]:
#For else
nums = [12,16,18,21,25,20]
for num in nums:
  if num%5 == 0:
    print(num,end=" ")
    break
  else:
    print("not found",end=" ")

print("\nFor else:")
nums = [12,16,18,21,29,25]
for num in nums:
  if num%5 == 0:
    print(num,end=" ")
    break
else:
  print("not found",end=" ")

not found not found not found not found 25 
For else:
25 

In [ ]:
num = 25 # int(input('Enter a number:'))
for i in range(2,num):
  if num%i == 0:
    print(num,"is not prime")
    break
else:
  print(num,"is prime")
import math as m

#Efficient code
def is_prime(n):
  if n<=1 or n%2==0 or n%3==0:
    return False
  if n<=3:
    return True
  for i in range(5, int(m.sqrt(n)), 6):
    if n%i==0 or n%(i+2)==0:
      return False
  return True
total = []
for i in range(1,num+1):
  if is_prime(i):
    print(i," ",end="")
    total.append(i)
print("\n",total)

25 is not prime
5  7  11  13  17  19  23  25  
 [5, 7, 11, 13, 17, 19, 23, 25]


###ARRAY

In [ ]:
from array import *
vals = array('i',[2,3,5,-3])
b = vals.itemsize
print(b)
for i in range(len(vals)):
  print(vals[i],end=" ")
print("")
for e in vals:
  print(e, end= " ")

4
2 3 5 -3 
2 3 5 -3 

In [ ]:
vals = array('i',[5,9,8,7])
newArr = vals
for e in newArr:
  print(e,end=" ")
newArr = array(vals.typecode, (a*a for a in vals))
print(newArr)

5 9 8 7 array('i', [25, 81, 64, 49])


In [ ]:
#Factorial
def factorial(n):
  res = 1
  for i in range(2,n+1):
    res = res*i
  return res

print(factorial(1))

def recursive(n):
  if n==0 or n==1:
    return 1
  else:
    return n*recursive(n-1)

print(recursive(5))

1
120


In [ ]:
from array import *
arr = array('i',[])
for e in range(5):
  arr.append(e)
print(arr)
a = arr.tolist
print(a)

array('i', [0, 1, 2, 3, 4])
<built-in method tolist of array.array object at 0x7ec12dc3fb00>


In [ ]:
from numpy import *
arr1 = array([2,2,3,3])
arr = array([2,2,3,3.0])
print(arr.dtype," ",arr)
print(arr1.dtype," ",arr1)

float64   [2. 2. 3. 3.]
int64   [2 2 3 3]


In [ ]:
#Linspace: divides a range of numbers by given parts
#Default parts is 50, if value not specified
arr = linspace(0,16,10 )
print(arr)
arr = linspace(0,16,17 )
print(arr)

[ 0.          1.77777778  3.55555556  5.33333333  7.11111111  8.88888889
 10.66666667 12.44444444 14.22222222 16.        ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


In [ ]:
#arange: the gaps between each number is specified for a given range
arr = arange(0,16,2)
print(arr)

[ 0  2  4  6  8 10 12 14]


In [ ]:
#logspace: space betwwen two numbers based on the log , and dividing into given
#parts
arr = logspace(0,40,5)
print(arr)
print('%.2f' %arr[4])

[1.e+00 1.e+10 1.e+20 1.e+30 1.e+40]
10000000000000000303786028427003666890752.00


In [ ]:
#zeros and ones
arr = zeros(5)
print(arr)
arr1 = ones(5,int)
print(arr1)

[0. 0. 0. 0. 0.]
[1 1 1 1 1]


In [ ]:
#
arr = array([1,6,3,4,5])
arr2 = array([1,2,3,4,5])
print(arr+arr2)
arr = arr + 5
print(arr)
print('sin:',sin(arr2))
print('sqrt:',sqrt(arr2))
print('sum:',sum(arr2))
print('max:',max(arr2))
print('sort:',sort(arr2))
print('concat:',concatenate([arr,arr2]))

[ 2  8  6  8 10]
[ 6 11  8  9 10]
sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]
sum: 15
max: 5
sort: [1 2 3 4 5]
concat: [ 6 11  8  9 10  1  2  3  4  5]


In [ ]:
from numpy import *
arr1 = array([1,2,3,42,3])
#Aliasing: single memory space with the same values when copied
arr2 = arr1
print(arr2)
print(id(arr1),id(arr2))

#To create a new array at different location
#1.Shallow copy
arr2 = arr1.view()
arr1[1] = 7
arr2[2] = 8

print('Shallow copy:values changed:',arr1,arr2)
print('Shallow copy:address is different:',id(arr1),id(arr2))
#2.Deep copy
arr2 = arr1.copy()
arr1[1] = 33
arr2[2] = 22
print('Deep copy:values changed:',arr1,arr2)
print('Deep copy:address is different:',id(arr1),id(arr2))

[ 1  2  3 42  3]
135910765177776 135910765177776
Shallow copy:values changed: [ 1  7  8 42  3] [ 1  7  8 42  3]
Shallow copy:address is different: 135910765177776 135910765178352
[ 1  7  8 42  3] <built-in method sort of numpy.ndarray object at 0x7b9c30e12df0>
Deep copy:values changed: [ 1 33  8 42  3] [ 1  7 22 42  3]
Deep copy:address is different: 135910765177776 135910765180560


In [ ]:
#ARRAYS
arr1 = array([ [1,2,3,2,3,2],
               [4,5,6,5,6,4] ])
arr2 = arr1.flatten()
print(arr2.reshape(3,4),'\n')
arr3 = arr2.reshape(2,2,3)
print(arr2,'\n2 arrays of 2X3:\n ' ,arr3)

[[1 2 3 2]
 [3 2 4 5]
 [6 5 6 4]] 

[1 2 3 2 3 2 4 5 6 5 6 4] 
2 arrays of 2X3:
  [[[1 2 3]
  [2 3 2]]

 [[4 5 6]
  [5 6 4]]]


In [ ]:
arr1 = array([ [1,2,3,2],
               [4,5,6,5] ])

mat1 = matrix(arr1)
#Output looks same but there can be many operations done
print(mat1)
#another way for matrix
mat2 = matrix('1 2 3; 3 4 4')
print(mat2)
#get diagonal elements
print(diagonal(mat2))
print(mat2.max())

[[1 2 3 2]
 [4 5 6 5]]
[[1 2 3]
 [3 4 4]]
[1 4]
4


In [ ]:
#Multiplying matrice
from numpy import *
a = random.rand(3,4)
b = random.rand(4,3)

#Input form user
#input()	Takes user input as a string
#.split()	Splits it into list of strings
#map(int, ...)	Converts strings to integers
#list(...)	Converts to list of integers
#mat.append(...)	Adds it as a new row to mat
mat = []
for _ in range(2):  # 2 rows example
#using _ as i is not needed
    mat.append(list(map(int, input().split())))
a = array(mat)


a = array([[2,3,4], [3,5,6]])
b = array([[2,3],[3,6], [2,3]])

x,y= matrix(a),matrix(b)
rows,cols,r = a.shape[0],b.shape[1],b.shape[0]
c= zeros((rows,cols))
for i in range(rows):
  for j in range(cols):
    for k in range(r):
      c[i][j]+= a[i][k]*b[k][j]

print(c)
#Convert array to matrix as integer format
z=matrix(c,int)
print(z)
#MArtix Multiplication is only possible on matrices, so x,y are matrix converted from a,b
print(x*y)


2 3 4
3 4 5
[[21. 36.]
 [33. 57.]]
[[21 36]
 [33 57]]
[[21 36]
 [33 57]]


In [ ]:
#Functions
#1.Immutable objects:values are not changed when changed inside a function
print('Immutable objects when modified in function:')
def update(x):
  print('before change', x,id(x))
  x=8
  print('after change ', x,id(x))
#Integer strings are immutable
a=3
print('before update',a,id(a))
update(a)
print('after update ',a,id(a))
#Passby value: value is not changed

#1.Mutable objects:values are changed when changed inside a function
print('Mutable objects when modified in function:')
def update1(x):
  print('before change', x,id(x))
  x[1]=3
  print('after change ', x,id(x))
#Integer strings are immutable
lst=[3 , 2,4]
print('before update',lst,id(lst))
update1(lst)
print('after update ',lst,id(lst))
#Passby value: value is not changed

Immutable objects when modified in function:
before update 3 10757800
before change 3 10757800
after change  8 10757960
after update  3 10757800
Mutable objects when modified in function:
before update [3, 2, 4] 138160298019264
before change [3, 2, 4] 138160298019264
after change  [3, 3, 4] 138160298019264
after update  [3, 3, 4] 138160298019264


In [ ]:
#Types of arguments
from numpy import *
#1.keyword argument
def person(name,age):
  print(name,age)
person(age='28',name='sup')

#2. default arguments
def person1(name,age=18):
  print(name,age)
person1('sup',28)
person1('sup')

#3. Variable length arguments
def sum(a,*b):
  c=a
  for i in b:
    c+=i
  print(c)
sum(5,6,10)

sup 28
sup 28
sup 18
21


In [ ]:
#Variable length argument with key
def person(name,*data):
 #data is tuple
  print(data)
person('sup',28,'Bang',9630)
def person1(name,**data):
 #**data is tuple with key
  print(data)
  for i,j in data.items():
    print(i,j)
person1('sup',age=28,city='Bang',num=9630)

(28, 'Bang', 9630)
{'age': 28, 'city': 'Bang', 'num': 9630}
age 28
city Bang
num 9630


In [ ]:
#Global keyword in Python
#Scope

def func():
  a = 15
  print('in func',a)
a = 10
func()
print('outisde fun',a)

#when declarin variable as global,it changes the value
#
a = 10
print(id(a))
def func():
  global a #any function made on global variable will reflect everywhere
 # global a #using a global variable
  x=globals()['a']
  a = 15
  print(id(a))

  print('in func',a)

func()
print('outisde fun',a)


in func 15
outisde fun 10
10758024
10758184
in func 15
outisde fun 15


In [ ]:
#Pass a list to a function
def func(lst):
  even,odd=0,0

  for i in lst:
    if i %2==0:
      even+=1
    else:
      odd+=1
  return even,odd

a = [2,3,4,5,3,4]
even,odd = func(a)
print("Even:{} and Odd:{}".format(even, odd))

Even:3 and Odd:3


In [ ]:
#Fibonacci series
def fibonacci(lst):
  y = []
  y.append(0)
  y.append(1)
  a,b=0,1
  for i in range(2,lst):
    c=a+b
    a=b
    b=c
    y.append(c)
  return y

res = fibonacci(10)
print(res)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [ ]:
#Factorial
def fact(n):
  res=1
  for i in range(1,n+1):
    res*=i
  return res
print(fact(4))
#Recursive function factorial
def fact(n):
  if n==0:
    return 1
  return n*fact(n-1)
res= fact(4)
print(res)

24
24


In [ ]:
#Lambda: Anonymus function
#Means function without name,which can have just one expression
f= lambda a,b:a+b
res = f(5,4)
print(res)

#Filter Map Reduce
nums = [1,2,3,4,5,6]

#Filter: to filter the value based on a condition
evens = list(filter(lambda n: n%2==0 ,nums))
print('Filter:',evens)
#Map:
doubles= list(map(lambda n:n*2,nums))
print('Map:',doubles)
#Reduce: to find one value
from functools import reduce
red = reduce(lambda x,y: x+y,doubles)
print('Reduce:',red)

9
Filter: [2, 4, 6]
Map: [2, 4, 6, 8, 10, 12]
Reduce: 42


In [ ]:
#decorators
def div(a,b):
  return a/b
def smart(func):
  def inner(a,b):
    if a<b:
      a,b = b,a
    return func(a,b)
  return inner

div1 = smart(div)
div1(2,4)

2.0

In [ ]:
class Computer:
    def config(self):
        print("i5,16GB")

a = '8'
print(type(a))
#str is an inbuilt class: see the output
#As everything is an object in Python
comp1 = Computer()
print(type(comp1))

#1.one way of calling a method
comp1.config()
#2.second way of calling method
Computer.config(comp1)
a=5
a.bit_length()

<class 'str'>
<class '__main__.Computer'>
i5,16GB
i5,16GB


3

In [ ]:
#OOPs

class Computer:
    #__init__is constructor
    def __init__(self,cpu,ram):
        self.cpu = cpu
        self.ram = ram

    def config(self):
        print(self.cpu,self.ram)

comp1 = Computer('i5',17)
comp2 = Computer('i7',20)

comp1.config()
comp2.config()

i5 17
i7 20


In [ ]:
#Constructor,Self and Comparing Objects
class computer:
  pass
c1 = computer()
c2 = computer()
print(id(c1))
print(id(c2))
#notice that it is differenc address for each object
#how much space does it take-> the size depends on the no. of variables
#and the size of it


class computer:
  def __init__(self):
    self.name = "Supr"
    self.age = 28
  def update(self):
    #Self will update only that particular object
    self.age = 30
  def compare(self,other):
    if self.age == other.age:
      return True
    else:
      return False
c1 = computer()
c2 = computer()
c1.name = 'PRav'
c1.update()
print(c1.name,c1.age)
print(c2.name,c2.age)

#Notice that second parameter is an object
if c1.compare(c2):
  pass
else:
  print('different age')


138264646464720
138264646451728
PRav 30
Supr 28
different age


In [ ]:
#TYPES OF VARIABLES
class car:
  #1.Class/static Variable
  wheels = 4
  def __init__(self):
    #Variables are defined in __init__
    #2.Instance variable
    self.mil = 10
    self.com = "BMW"

c1 = car()
c2 = car()
c1.mil = 13
#Notice how the instance an class/static variables are called
print(c1.mil,c1.wheels)
print(c2.mil,car.wheels)

#Namespace: is an area where you create and store object/variable

13 4
10 4


In [ ]:
#TYPES OF METHODS
#Instance,Class and Static
class student:
  school = 'KV'
  def __init__(self,m1,m2,m3):
    self.m1 = m1
    self.m2 = m2
    self.m3 = m3
 #1.Instance method : works with instance variables
  def avg(self):
    return (self.m1 + self.m2 + self.m3 )/3
  #1a.Getters
  def get_m1(self):
    return self.m1
  #1b.Setters
  def set_m1(self,value):
    self.m1 = value
    return self.m1
  #2.Class method : works with class variables
  @classmethod   #decorator
  def getSchool(cls):
    return cls.school
  #3.Static method: we don't use any variable
  @staticmethod
  def info():
    print("This is studdent class")

s1 = student(2,3,5)
s2 = student(66,66,44)

print(s1.avg())
print(s2.avg())
#Types of intance methods
#1a.Accessor method(Getters): when we only fethc the value of instance variable
#1b.Mutator method(Setters): when we update the """

#2.Calling Class method
print(student.getSchool())

#3.Calling static method
student.info()


3.3333333333333335
58.666666666666664
KV
This is studdent class


In [ ]:
#INNER CLASS
class student:

  def __init__(self,name,rollno):
    self.name = name
    self.rollno = rollno
    #1.call the inner class inside outer class using self
    self.lap = self.laptop()
  def show(self):
    print(self.name,self.rollno)
    print(self.lap.brand,self.laptop().ram)
   #class inside class
  class  laptop:
    def __init__(self):
      self.brand = 'HP'
      self.ram = '23'

    def show(self):
      print(self.brand)

s1 = student('sup',1)
s2 = student('prav',29)

s1.show()
#Calling inner class attribute
s2.lap.brand = 'apple'
s2.show()
#2.call the inner class outside outer class using outer class name
lap3 = student.laptop()
lap3.show()

sup 1
HP 23
prav 29
apple 23
HP


In [ ]:
#Inheritance
class A: #Super class
  def feature1(self):
    print("Feature 1 working")
  def feature2(self):
    print("Feature 2 working")
class B(A): #Class B is inheriting A #Sub class
  def feature3(self):
    print("Feature 3 working")
  def feature4(self):
    print("Feature 4 working")
class C(B): #Multilevel inheritance
  def feature5(self):
    print("Feature 5 working")
class E: #Super class
  def feature1(self):
    print("Feature 1 working")
class D(A,E): #Multiple Inheritance
  def feat(self):
    print("class C")
a1 = A()
a1.feature1()
a1.feature2()

b1 = B()
b1.feature2()

c1 = B()
c1.feature2()

Feature 1 working
Feature 2 working
Feature 2 working
Feature 2 working


In [ ]:
#Constructor in inheritance
class A: #Super class
  def __init__(self):
    print("Constructor of A")
  def feature1(self):
    print("Feature 1 working")
  def feature2(self):
    print("Feature 2 working")
class B(A): #Sub class
  def __init__(self):
    #how to call _init_ of A
    super().__init__()
    print("Constructor of B")
  def feature3(self):
    print("Feature 3 working")
  def feature4(self):
    print("Feature 4 working")

#If there is no constructore of B constructor of A is exectuted
#if there is constructor in both , B constructor is calles not A constructore

b1 = B()



Constructor of A
Constructor of B


In [ ]:
#MRO: Method resolution order
class A:
  def __init__(self):
    print("Constructor of A")
  def feature1(self):
    print("Feature 1 of A working")
class B():
  def __init__(self):
    print("Constructor of B")
  def feature1(self):
    print("Feature 1 of B working")
class C(A,B): #Multiple inheritance
  def __init__(self):
    print("Constructor of C")
    super().__init__()
  def feature5(self):
    print("Feature 5 working")


c1 = C()
c1.feature1()

#MEthod resoltion order:
#The inheritance starts from left to right
#so only A gets called here
#first constructor of C is called and then Super class constructore from lef to right

Constructor of C
Constructor of A
Feature 1 of A working


In [ ]:
#Polymorphism: 1. Duck typing
#Polymorphism is one thing and multiple forms
#Dynamic type: type can be mentioned later
#Based on the saying: "If it looks like a duck, swims like a duck, and quacks
#like a duck, then it probably is a duck.
#Duck typing means that Python doesn't check an object’s type to determine if it can be used for a specific purpose.
#Instead, it checks whether the object has the required behavior (methods or properties).
class pycharm:
  def execute(self):
    print("executed")
class myide:
  def execute(self):
    print(" better executed")
class laptop:
  def code(self,ide):
    ide.execute()
ide = pycharm()
lap1 = laptop()
lap1.code(ide)
ide = myide()
lap2 = laptop()
lap2.code(ide)

executed
 better executed


In [ ]:
#Polymorphism: 2. Operator overloading
#Operator Overloading in Python means giving special meaning to standard operators (like +, -, ==, etc.)
#so they can work with user-defined objects (like classes) in a way that’s intuitive.
a= 5
b= 6
print(a+b)
print(int.__add__(a,b))

a= '5'
b= '6'
print(a+b)
print(str.__add__(a,b))
#All the operators behid the scene they act as methods

class student:
  def __init__(self,m1,m2):
    self.m1 = m1
    self.m2 = m2
  def __add__(self,other): #called when operator + is used
    m1 = self.m1 + other.m1
    m2 = self.m2 + other.m2
    s3 = student(m1,m2)
    return s3
  def __gt__(self,other):
    r1 = self.m1 + self.m2
    r2 = other.m1 + other.m2
    if r1>r2:
      return True
    else:
      return False
  def __str__(self):
    return 'm1:{}m2:{}'.format(self.m1,self.m2)
s1 = student(2,4)
s2 = student(4,6)
s3 = s1 + s2 #gives error when __add__method not mentioned
# -->student.__add_(s1,s2)
print(s3.m1,s3.m2)

if s1 > s2:
  print("s1 wins")
else:
  print("s2 wins")

#__str__ :
a=9
print('a:',a.__str__())

print(s1)

11
11
56
56
6 10
s2 wins
a 9
m1:2m2:4


In [ ]:
#Polymorphism: 3. Method Overloading:method with same name , but different parameters
#not possible in python because 2methods with sam ename is not possible
#Having multiple methods with the same name but different arguments.
class student:
  def sum(self,a=0,b=0,c=0):
    return a+b+c

s1 = student()
#Indirectly using method overriding
print(s1.sum(3,2))

5


In [ ]:
#Polymorphism: 3. Method Overriding
#When a child class provides a specific implementation of a method that is already
#defined in its parent class.
class A:
  def show(self):
    print("In A Show")
class B(A):
  def show(self):
    print("In B Show")

b1 = B()
b1.show() #Sub class overrides Super class

In B Show


In [ ]:
#Abstract Class and Abstract Method
#Python by default does not support Abstract classes
#Abstract class has atleast one abstract method
#We cannot create object for Abstract class
from abc import ABC, abstractmethod
class comp(ABC):
  @abstractmethod #need to use decorator for abstract
  def proc(self):
   pass #method just defined , not implemented
class lap(comp):
  def proc(self):
    print("run")
#c1 = comp() #error cant instantiates
l1 = lap()#Runs

#Use of Abstract class? :  In Python, abstract classes are used to define a
# common interface or blueprint for other classes, without implementing full
#functionality. They’re part of Python’s object-oriented programming (OOP) model
#and help enforce consistent behavior across subclasses.
#Abstract class can have both abstract methods and normal methods
#Interfaces can have only abstract methods and no attributes

In [ ]:
#Iterator
nums = [3,6,8,9]
it = iter(nums)
print(it.__next__())
print(it.__next__())

print(next(it))

#Own iterator function
print("User defined iterator:")
class topten:
  def __init__(self):
    self.num = 1
  def __iter__(self):
    return self
  def __next__(self):
    if self.num<=10:
      val = self.num
      self.num += 1
      return val
    else:
      raise StopIteration

values = topten()
print(values.__next__())
for i in values: #starts from 2 as next is already executed
  print(i,end=" ")

3
6
8
User defined iterator:
1
2 3 4 5 6 7 8 9 10 

In [ ]:
#Generator
def topten():
  yield 5 #special function that makes a function as generator
  yield 4
  yield 2
  yield 7
values = topten()
print(values.__next__())
print(values.__next__())
for i in values:
  print("for:",i)

print("")
def topten():
  n=1
  while n<=10:
    sq =n*n
    yield sq
    n+=1
values = topten()
for i in values:
  print(i, end=" ")

#Purpose: when fetching 1000 records, when we want to work with one value at a time
#instead of fetching all

5
4
for: 2
for: 7

1 4 9 16 25 36 49 64 81 100 

In [ ]:
#Exception handling
a,b=5,0
try:
  print(a/b)
  print("Notice this does not get executed")
except ZeroDivisionError as e:
  print("Error divide by zero\n",e)
except ValueError as e:
  print("Invalid Input\n",e)
except Exception as e:
  print("General error Something went wrong")
finally:
  print("close file")
#executes in spite of excception or not
print("Bye")

Error divide by zero
 division by zero
close file
Bye


In [ ]:
#Multithreading
#Check pycharm file multithreading.py
from time import sleep
from threading import *
class hello(Thread):
  def run(self): #Inside Thread class there is run method
    for i in range(5):
      print("Hello")
      sleep(1)

class hi(Thread):
  def run(self):
    for i in range(5):
      print("Hi")
      sleep(1)

t1 = hello()
t2 = hi()

t1.start() #Use start method which will call run()
sleep(0.2)
t2.start()
#there are 3 threads main thread, t1 thread, t2 thread
print("before Bye") #Main prints this

Hello
Hi
Bye


In [ ]:
#Comments
#"""-->used for documentation , dont use,
#Use Hash for comments

In [ ]:
#Linear search
pos = -1
def search(list,n):
  i=0
  while i<(len(list)):
    if list[i] == n:
      globals()['pos'] = i
      return True
    i+=1
  return False
list = [8,5,6,7,9]
n=9
if search(list,n):
  print("Found at",pos)
else:
  print("not found")

Found as 4


In [ ]:
#Binary search is Faster
pos  = -1
def bin_Search(list,n):
  l = 0
  u = len(list)-1
  while l<=u:
    m = (l+u)//2
    if list[m] == n:
      globals()['pos'] = m
      return True
    elif list[m] < n:
      l = m +1
    else:
      u = m-1
  return False
list = [8,5,6,7,9]
if bin_Search(list,9):
  print("found at",pos)
else:
  print("not found")

found at 4


In [ ]:
#Bubble sort
def bubble_sort(l):
  for i in range(len(l)-1,0,-1):
    for j in range(i):
      if l[j]>l[j+1]:
        l[j],l[j+1] = l[j+1],l[j]
  return l

list = [4,6,2,8,6,9]
print(bubble_sort(list))
#swaping consumes more power less efficicient

[2, 4, 6, 6, 8, 9]


In [ ]:
#Selection sort
def sel_sort(l):
  for i in range((len(l)-1)):
    min = i
    for j in range(i,len(l)):
      if l[j]<l[min]:
        min=j
    l[i],l[min] = l[min],l[i]
  return l

list = [4,6,2,8,6,9]
print(sel_sort(list))
#swapping is less here

[2, 4, 6, 6, 8, 9]


In [1]:
#Merge sort
def merge_sort(list):
  if len(list) <= 1:
    return list

  mid = len(list) // 2

  left  = merge_sort(list[:mid])
  right = merge_sort(list[mid:])

  return merge(left,right)
def merge(left, right):

  result = []
  i=j=0
  while i<len(left) and j<len(right):
    if left[i] <= right[j]:
      result.append(left[i])
      i=i+1
    else:
      result.append(right[j])
      j=j+1

  # Append remaining elements
  result.extend(left[i:])
  result.extend(right[j:])

  return result


if __name__ == "__main__":
  arr = [5, 2, 9, 1, 6, 3]
  sorted_arr = merge_sort(arr)
  print(sorted_arr)


[1, 2, 3, 5, 6, 9]


In [2]:
#Quick sort
def quick_sort(list):
  if len(list) <= 1:
    return list

  pivot = list[0]
  left = [x for x in list[1:] if x<=pivot]
  right = [x for x in list[1:] if x>pivot]

  return quick_sort(left) + [pivot] + quick_sort(right)

arr = [7, 2, 1, 6, 8, 5, 3, 4]
sorted_arr = quick_sort(arr)
print(sorted_arr)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
#Zip function
names = ("Prav", "sup")
comps = ("apple","lenvo")
zipped = list(zip(names,comps))

print(zipped)

zipped2 = set(zip(names,comps))
print(zipped)

zipped = dict(zip(names,comps))
print(zipped)

for (a,b) in zipped2:
  print(a,b)

[('Prav', 'apple'), ('sup', 'lenvo')]
[('Prav', 'apple'), ('sup', 'lenvo')]
{'Prav': 'apple', 'sup': 'lenvo'}
sup lenvo
Prav apple


In [ ]:
#String manipulation
name = 'supraja aravamudhan'

print(len(name))

print(name.find('a'))

19
4


In [ ]:
#Scope Resolution
x = "global"
def outer():
    x = "enclosing"
    def inner():
        x = "local"
        print(x)  # local wins
    inner()
outer()

#Global
x = 10
def update():
    global x
    x = 20
update()
print(x)  # 20

#NonLocal
def outer():
    x = "outer"
    def inner():
        nonlocal x
        x = "inner"
    inner()
    print(x)
outer()  # inner

local
20
inner


In [ ]:
#Enumerate and Zip fucntion

#enumerate() adds a counter to an iterable and returns it as an enumerate object (which is iterable).
fruits = ['apple', 'banana', 'cherry']
for index, fruit in enumerate(fruits,start=1):
    print(index, fruit)

#zip() combines multiple iterables (like lists or tuples) into tuples, element-wise.
names = ['Alice', 'Bob', 'Charlie']
scores = [85, 90, 95]

for name, score in zip(names, scores):
    print(f'{name} scored {score}')

#Compbined example
names = ['Alice', 'Bob', 'Charlie']
scores = [85, 90, 95]

for i, (name, score) in enumerate(zip(names, scores), start=1):
    print(f'{i}. {name} scored {score}')



1 apple
2 banana
3 cherry
Alice scored 85
Bob scored 90
Charlie scored 95
1. Alice scored 85
2. Bob scored 90
3. Charlie scored 95


In [ ]:
#*args: Stands for "arguments"
#       Allows you to pass any number of positional arguments to a function.
#       Internally treated as a tuple
def add_numbers(*args):
    total = sum(args)
    #args.count
    print("Sum:", total)

add_numbers(1, 2, 3)       # Sum: 6
add_numbers(5, 10, 15, 20) # Sum: 50

#*kwargs: Stands for "keyword arguments"
#         Allows you to pass any number of named arguments (key-value pairs).
#         Internally treated as a dictionary.
def print_user_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")
    #kwargs.pop
print_user_info(name="Alice", age=30, city="Austin")


Sum: 6
Sum: 50
name: Alice
age: 30
city: Austin


In [ ]:
#Dunder methods
class Book:
    def __init__(self, title, pages):
        self.title = title
        self.pages = pages

    def __str__(self):
        return f"{self.title} ({self.pages} pages)"

    def __len__(self):
        return self.pages

    def __eq__(self, other):
        return self.pages == other.pages

book1 = Book("Python 101", 250)
book2 = Book("ML Basics", 250)

print(str(book1))        # Python 101 (250 pages)
print(len(book1))        # 250
print(book1 == book2)    # True


Python 101 (250 pages)
250
True


In [ ]:
#Regular expressions
import re
result = re.search(r'\d+', 'Order 12345')
print('1.',result.group())

#Finding 4 letter words
result = re.findall(r'\b\w{4}\b', 'This is a test line with four word terms')
print('2.',result)

result = re.sub(r'\s+', '-', 'hello   world python')  # Output: 'hello-world-python'
print('3.',result)

pattern = re.compile(r'\d{3}-\d{2}-\d{4}')
result = pattern.match('123-45-6789')  # Valid SSN format
print('4.',result)

#Raw strings treat backslashes literally, avoiding double escaping.
#Example: r"\d+" is better than "\\d+"

1. 12345
2. ['This', 'test', 'line', 'with', 'four', 'word']
3. hello-world-python
4. <re.Match object; span=(0, 11), match='123-45-6789'>


In [13]:
#Collection module

#A Counter is a dictionary subclass that counts hashable objects.
from collections import Counter


fruits = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple']
count = Counter(fruits)
print(count)

print(count.most_common(1))
print(count['banana'])

#A defaultdict is like a regular dict, but returns a default value when a key
#is missing (avoids KeyError).

from collections import defaultdict

group = defaultdict(list)
group['a'].append(1)
group['a'].append(2)
group['b'].append(1)

print(group['a'], group['c'])

#A deque (double-ended queue) allows fast appends and pops from both ends —
#faster than a list.
from collections import deque

dq = deque([1, 2, 3])
dq.append(4)       # right end
dq.appendleft(0)   # left end
print(dq)          # deque([0, 1, 2, 3, 4])

dq.pop()           # 4
dq.popleft()       # 0
print(dq)

#Other function: rotate(n): rotates elements right by n

Counter({'apple': 3, 'banana': 2, 'orange': 1})
[('apple', 3)]
2
[1, 2] []
deque([0, 1, 2, 3, 4])
deque([1, 2, 3])


In [13]:
#Itertools:
#The itertools module provides a collection of fast, memory-efficient tools for
# working with iterators. These tools are useful for looping, filtering, grouping,
#and generating combinations or permutations — especially with large datasets.

#Count:Infinite counter generator
from itertools import count
print("Count:")
for i in count(5,2):
  print(i,end=" ")
  if i>=12:
    break
#Cycle:Repeats elements of the iterable endlessly.
from itertools import cycle
print("\n\nCycle:")
i=0
for item in cycle(['A', 'B', 'C']):
    print(item,end=" ")
    if i > 12:
      break
    i+=1

#Repeat:Repeats a value a fixed number of times.
from itertools import repeat
print("\n\nRepeat:")
for x in repeat("Hi", 3):
    print(x, end=" ")

#Chain:Flattens multiple iterables into a single sequence.
from itertools import chain
print("\n\nChain:")
print(list(chain([1, 2], ['a', 'b'])))
# Output: [1, 2, 'a', 'b']

#Combinations: Returns all r-length combinations (no repeats, order doesn't matter).
from itertools import combinations
print("\nCombinations:")
print(list(combinations('ABCD', 2)))

#Permutations: Returns all r-length permutations (order matters).
from itertools import permutations
print("\nPermutations:")
print(list(permutations('ABC', 2)))

#Product: Cartesian product of input iterables.
from itertools import product
print("\nCartesian product:")
print(list(product([1, 2], ['A', 'B'])))

#Groupby: Groups consecutive elements based on a key function.
from itertools import groupby
print("\nGroup by:")
data = 'aaabbbccaa'
for key, group in groupby(data):
    print(key, list(group))

#Accumulate
from itertools import accumulate
print("\nAccumulate:")
data = [1, 2, 3, 4, 5]
accumulated = accumulate(data)
for item in accumulated:
  print(item, end=" ")

Count:
5 7 9 11 13 

Cycle:
A B C A B C A B C A B C A B 

Repeat:
Hi Hi Hi 

Chain:
[1, 2, 'a', 'b']

Combinations:
[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

Permutations:
[('A', 'B'), ('A', 'C'), ('B', 'A'), ('B', 'C'), ('C', 'A'), ('C', 'B')]

Cartesian product:
[(1, 'A'), (1, 'B'), (2, 'A'), (2, 'B')]

Group by:
a ['a', 'a', 'a']
b ['b', 'b', 'b']
c ['c', 'c']
a ['a', 'a']

Accumulate:
1 3 6 10 15 

In [17]:
#Type hinting lets you specify expected data types for variables, function arguments,
#and return values. It improves code readability, IDE support, and static analysis
#using tools like mypy, pyright, and pylance.

#Basic Type hint
def greet(name: str) -> str:
    return f"Hello, {name}"
greet('Supraja')

from typing import List, Dict, Optional, Union
def add_numbers(numbers: List[int]) -> int:
  return sum(numbers)

#From python 3.9 builtin type hint , no need to use from typing
def square(numb:List[int]) -> List[int]:
  return [x**2 for x in numb ]

**Module related code, file handling handled in PYCharm/GitHub PythonBasics_Pycharm**